### ISSUE TITLE
비로그인 사용자가 Add화면 진입 후 로그인을 진행하면 갤러리로 이동하기

### ISSUE THREAD

**Issue by SeoSeungHwan** [SeoSeungHwan/DIDA#66]
비로그인 사용자가 Add화면 진입 후 로그인을 진행하면 갤러리로 이동하기
- 현재는 갤러리로 이동하는것이 아닌 갤러리다음스탭인 제목, 내용 작성화면으로 이동(사진없는상태)

**Comment by Gyuil-Hwnag** [comment]
사진 체크에 대한 확인을 하는것으로 수정

**Comment by Gyuil-Hwnag** [comment]
유저의 지갑을 체크하는 것을 onResume()에서 호출하도록 수정
