### ISSUE TITLE
토큰만료 시 API호출 IllegalExceptionError 발생

### ISSUE THREAD

**Issue by SeoSeungHwan** [SeoSeungHwan/DIDA#67]
<img width="1574" alt="스크린샷 2022-11-07 오전 11 45 29" src="https://user-images.githubusercontent.com/25413894/200231700-e8252118-94d4-4992-ab1d-933b2e7db167.png">

**Comment by Gyuil-Hwnag** [comment]
기존 Moshi Builder 사용시 Serialize를 Json:name()으로 하던 부분 @Serialize로 수정
