### ISSUE TITLE
Mypage Glide 에러

### ISSUE THREAD

**Issue by Gyuil-Hwnag** [SeoSeungHwan/DIDA#9]
D/ContentValues: bindImageFromURL: https://movie-phinf.pstatic.net/20190417_250/1555465284425i6WQE_JPEG/movie_image.jpg?type=m665_443_2
I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.

**Comment by SeoSeungHwan** [comment]
Intent 화면 전환 무한반복 문제로 확인되어 해결했습니다.
